# Generated by Django 5.0 on 2024-02-29 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_station_alter_foundid_station_alter_user_station'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='first_name',
            new_name='firstname',
        ),
    ]
