# Generated by Django 5.0 on 2024-02-29 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_first_name_user_firstname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='last_name',
            new_name='lastname',
        ),
    ]
