# Generated by Django 4.2.10 on 2024-05-16 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_last_name_user_lastname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foundid',
            name='date_found',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
